apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-api
  template:
    metadata:
      labels:
        app: transactions-api
    spec:
      containers:
      - name: transactions-api
        image: us-central1-docker.pkg.dev/datasynpipeline2025/my-app-repo/data-sync-api
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "datasynpipeline2025"
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-api-service
spec:
  selector:
    app: transactions-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
